-- ==============================================================
-- Database Schema for Champuchino Cafe Reservation System
-- Designed for Supabase (PostgreSQL)
-- ==============================================================

-- เปิดใช้งาน UUID extension (ถ้ายังไม่เปิด)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Table: users (ข้อมูลลูกค้าและแอดมิน)
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    line_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'student', -- 'student', 'lecturer', 'staff', 'admin'
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: cafe_tables (ข้อมูลโต๊ะ)
CREATE TABLE cafe_tables (
    id INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    table_number INT2 NOT NULL,
    capacity INT2 DEFAULT 8,
    status TEXT DEFAULT 'available' -- 'available', 'maintenance'
);

-- 3. Table: bookings (ข้อมูลการจอง)
CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    table_id INT8 REFERENCES cafe_tables(id) ON DELETE CASCADE,
    booking_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    guest_count INT2 NOT NULL CHECK (guest_count > 0 AND guest_count <= 8),
    status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'cancelled'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================
-- Mock Data (ข้อมูลจำลอง)
-- ==============================================================

-- ใส่ข้อมูลโต๊ะตั้งต้น 4 โต๊ะตามที่ออกแบบไว้
INSERT INTO cafe_tables (table_number, capacity, status) VALUES
(1, 8, 'available'),
(2, 8, 'available'),
(3, 8, 'available'),
(4, 8, 'maintenance');

-- ==============================================================
-- Row Level Security (RLS) Setup
-- ==============================================================

-- เปิดใช้งาน RLS สำหรับความปลอดภัย
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE cafe_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- 1. Policies ของ users
-- ให้ user แต่ละคนมองเห็นและแก้ไขเฉพาะข้อมูลของตัวเองได้ (ใช้ auth.uid() ของ Supabase)
CREATE POLICY "Users can view own data" ON users
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own data" ON users
    FOR UPDATE USING (auth.uid() = id);

-- 2. Policies ของ cafe_tables
-- ให้ทุกคนที่เข้าเว็บ (public) สามารถดูข้อมูลโต๊ะว่างได้
CREATE POLICY "Public can view tables" ON cafe_tables
    FOR SELECT USING (true);

-- 3. Policies ของ bookings
-- ให้ทุกคนสามารถดูคิวการจองได้ (เพื่อเช็คเวลาที่ว่าง)
CREATE POLICY "Public can view bookings" ON bookings
    FOR SELECT USING (true);

-- ให้ user สามารถเพิ่มคิวจองได้ แต่ต้องเป็น id ของตัวเองเท่านั้น
CREATE POLICY "Users can insert own bookings" ON bookings
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ให้ user แก้ไข (ยกเลิก) คิวของตัวเองได้
CREATE POLICY "Users can update own bookings" ON bookings
    FOR UPDATE USING (auth.uid() = user_id);

-- ==============================================================
-- Food & Beverage Pre-order Schema (ระบบสั่งอาหารล่วงหน้า)
-- ==============================================================

-- 4. Table: menu_categories (หมวดหมู่เมนู)
CREATE TABLE menu_categories (
    id INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

-- 5. Table: menu_items (รายการเมนูอาหาร/เครื่องดื่ม)
CREATE TABLE menu_items (
    id INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INT8 REFERENCES menu_categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    image_url TEXT,
    is_available BOOLEAN DEFAULT TRUE
);

-- 6. Table: booking_orders (รายการอาหารที่สั่งพร้อมการจอง)
CREATE TABLE booking_orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    booking_id UUID REFERENCES bookings(id) ON DELETE CASCADE,
    menu_item_id INT8 REFERENCES menu_items(id) ON DELETE CASCADE,
    quantity INT2 NOT NULL CHECK (quantity > 0),
    price_at_time NUMERIC(10, 2) NOT NULL -- เก็บราคา ณ วันที่สั่ง ป้องกันราคาเปลี่ยนในอนาคต
);

-- ==============================================================
-- Mock Data for Menu
-- ==============================================================
INSERT INTO menu_categories (name) VALUES ('Coffee'), ('Tea'), ('Bakery');

INSERT INTO menu_items (category_id, name, description, price, image_url) VALUES
(1, 'Classic Espresso', 'เอสเพรสโซ่เข้มข้น หอมกรุ่นด้วยครีม่าสีทอง', 85.00, 'images/espresso.png'),
(1, 'Signature Latte Art', 'ลาเต้รสนุ่ม ผสานศิลปะบนฟองนม', 110.00, 'images/latte.png'),
(1, 'Iced Caramel Macchiato', 'มัคคิอาโต้เย็น เลเยอร์คาราเมลหอมหวาน', 125.00, 'images/macchiato.png'),
(2, 'Iced Matcha Latte', 'มัทฉะพรีเมียมนำเข้าจากญี่ปุ่น', 120.00, 'images/matcha.png'),
(2, 'Hot Earl Grey Tea', 'ชาเอิร์ลเกรย์ร้อนกรุ่นๆ กลิ่นหอมละมุน', 95.00, 'images/earlgrey.png'),
(3, 'Butter Croissant', 'ครัวซองต์เนยสดแท้ แป้งกรอบนอกนุ่มใน', 75.00, 'images/croissant.png'),
(3, 'Blueberry Muffin', 'มัฟฟินบลูเบอร์รี่เนื้อนุ่ม อัดแน่นด้วยเบอร์รี่', 65.00, 'images/muffin.png');

-- ==============================================================
-- RLS Setup for Pre-order
-- ==============================================================
ALTER TABLE menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view menu categories" ON menu_categories FOR SELECT USING (true);
CREATE POLICY "Public can view menu items" ON menu_items FOR SELECT USING (true);

-- ให้ User สามารถจัดการรายการอาหารในคิวจองของตัวเองได้
CREATE POLICY "Users can manage their own booking orders" ON booking_orders 
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM bookings 
      WHERE bookings.id = booking_orders.booking_id 
      AND bookings.user_id = auth.uid()
    )
  );
